import streamlit as st
import joblib as jb
from streamlit_option_menu import option_menu

RF=jb.load(open('C:/Users/Admin/Desktop/SEM 5 project/clfRF_model.pkl','rb'))

with st.sidebar:
    selected=option_menu("Disease Prediction and Specilist Selection",
                         ['Disease Prediction',
                          'Consult Specialist'],
                         icons=['clipboard2-pulse-fill','heart-pulse-fill'],
                         default_index=0
    )

Symptom1=None
Symptom2=None
Symptom3=None
Symptom4=None
Symptom5=None
Symptom6=None

data = [0] * 131

d1 = {
   "abdominal pain"	:	0	,
"abnormal menstruation"	:	1	,
       "acidity"	:	2	,
        "acute liver failure"	:	3	,
        "altered sensorium"	:	4	,
        "anxiety"	:	5	,
        "back pain"	:	6	,
        "belly pain"	:	7	,
        "blackheads"	:	8	,
        "bladder discomfort"	:	9	,
        "blister"	:	10	,
        "blood in sputum"	:	11	,
        "bloody stool"	:	12	,
        "blurred and distorted vision"	:	13	,
        "breathlessness"	:	14	,
        "brittle nails"	:	15	,
        "bruising"	:	16	,
        "burning micturition"	:	17	,
        "chest pain"	:	18	,
        "chills"	:	19	,
        "cold hands and feets"	:	20	,
        "coma"	:	21	,
        "congestion"	:	22	,
        "constipation"	:	23	,
        "continuous feel of urine"	:	24	,
        "continuous sneezing"	:	25	,
        "cough"	:	26	,
        "cramps"	:	27	,
        "dark urine"	:	28	,
        "dehydration"	:	29	,
        "depression"	:	30	,
        "diarrhoea"	:	31	,
        "dischromic patches"	:	32	,
        "distention of abdomen"	:	33	,
        "dizziness"	:	34	,
        "drying and tingling lips"	:	35	,
        "enlarged thyroid"	:	36	,
        "excessive hunger"	:	37	,
        "extra marital contacts"	:	38	,
        "family history"	:	39	,
        "fast heart rate"	:	40	,
        "fatigue"	:	41	,
        "fluid overload"	:	42	,
        "foul smell of urine"	:	43	,
        "headache"	:	44	,
        "high fever"	:	45	,
        "hip joint pain"	:	46	,
        "history of alcohol consumption"	:	47	,
        "increased appetite"	:	48	,
        "indigestion"	:	49	,
        "inflammatory nails"	:	50	,
        "internal itching"	:	51	,
        "irregular sugar level"	:	52	,
        "irritability"	:	53	,
        "irritation in anus"	:	54	,
        "itching"	:	55	,
        "joint pain"	:	56	,
        "knee pain"	:	57	,
        "lack of concentration"	:	58	,
        "lethargy"	:	59	,
        "loss of appetite"	:	60	,
        "loss of balance"	:	61	,
        "loss of smell"	:	62	,
        "malaise"	:	63	,
        "mild fever"	:	64	,
        "mood swings"	:	65	,
        "movement stiffness"	:	66	,
        "mucoid sputum"	:	67	,
        "muscle pain"	:	68	,
        "muscle wasting"	:	69	,
        "muscle weakness"	:	70	,
        "nausea"	:	71	,
        "neck pain"	:	72	,
        "nodal skin eruptions"	:	73	,
        "obesity"	:	74	,
        "pain behind the eyes"	:	75	,
        "pain during bowel movements"	:	76	,
        "pain in anal region"	:	77	,
        "painful walking"	:	78	,
        "palpitations"	:	79	,
        "passage of gases"	:	80	,
        "patches in throat"	:	81	,
        "phlegm"	:	82	,
        "polyuria"	:	83	,
        "prognosis"	:	84	,
        "prominent veins on calf"	:	85	,
        "puffy face and eyes"	:	86	,
        "pus filled pimples"	:	87	,
        "receiving blood transfusion"	:	88	,
        "receiving unsterile injections"	:	89	,
        "red sore around nose"	:	90	,
        "red spots over body"	:	91	,
        "redness of eyes"	:	92	,
        "restlessness"	:	93	,
        "runny nose"	:	94	,
        "rusty sputum"	:	95	,
        "scurring"	:	96	,
        "shivering"	:	97	,
        "silver like dusting"	:	98	,
        "sinus pressure"	:	99	,
        "skin peeling"	:	100	,
        "skin rash"	:	101	,
        "slurred speech"	:	102	,
        "small dents in nails"	:	103	,
        "spinning movements"	:	104	,
        "spotting urination"	:	105	,
        "stiff neck"	:	106	,
        "stomach bleeding"	:	107	,
        "stomach pain"	:	108	,
        "sunken eyes"	:	109	,
        "sweating"	:	110	,
        "swelled lymph nodes"	:	111	,
        "swelling joints"	:	112	,
        "swelling of stomach"	:	113	,
        "swollen blood vessels"	:	114	,
        "swollen extremeties"	:	115	,
        "swollen legs"	:	116	,
        "throat irritation"	:	117	,
        "toxic look (typhos)"	:	118	,
        "ulcers on tongue"	:	119	,
        "unsteadiness"	:	120	,
        "visual disturbances"	:	121	,
        "vomiting"	:	122	,
        "watering from eyes"	:	123	,
        "weakness in limbs"	:	124	,
        "weakness of one body side"	:	125	,
        "weight gain"	:	126	,
        "weight loss"	:	127	,
        "yellow crust ooze"	:	128	,
        "yellow urine"	:	129	,
        "yellowing of eyes"	:	130	,
        "yellowish skin"	:	131	

}


if(selected=='Disease Prediction'):
    st.title('Disease Prediction Uising Random Forest in ML')
    
    options = {

    "Abdominal pain": "abdominal_pain",
    "Abnormal menstruation":"abnormal_menstruation",
    "acidity"	:	    "acidity"	,
    "acute liver failure"	:	    "acute_liver_failure"	,
    "altered sensorium"	:	    "altered_sensorium"	,
    "anxiety"	:	    "anxiety"	,
    "back pain"	:	    "back_pain"	,
    "belly pain"	:	    "belly_pain"	,
    "blackheads"	:	    "blackheads"	,
    "bladder discomfort"	:	    "bladder_discomfort"	,
    "blister"	:	    "blister"	,
    "blood in sputum"	:	    "blood_in_sputum"	,
    "bloody stool"	:	    "bloody_stool"	,
    "blurred and distorted vision"	:	    "blurred_and_distorted_vision"	,
    "breathlessness"	:	    "breathlessness"	,
    "brittle nails"	:	    "brittle_nails"	,
    "bruising"	:	    "bruising"	,
    "burning micturition"	:	    "burning_micturition"	,
    "chest pain"	:	    "chest_pain"	,
    "chills"	:	    "chills"	,
    "cold hands and feets"	:	    "cold_hands_and_feets"	,
    "coma"	:	    "coma"	,
    "congestion"	:	    "congestion"	,
    "constipation"	:	    "constipation"	,
    "continuous feel of urine"	:	    "continuous_feel_of_urine"	,
    "continuous sneezing"	:	    "continuous_sneezing"	,
    "cough"	:	    "cough"	,
    "cramps"	:	    "cramps"	,
    "dark urine"	:	    "dark_urine"	,
    "dehydration"	:	    "dehydration"	,
    "depression"	:	    "depression"	,
    "diarrhoea"	:	    "diarrhoea"	,
    "dischromic patches"	:	    "dischromic _patches"	,
    "distention of abdomen"	:	    "distention_of_abdomen"	,
    "dizziness"	:	    "dizziness"	,
    "drying and tingling lips"	:	    "drying_and_tingling_lips"	,
    "enlarged thyroid"	:	    "enlarged_thyroid"	,
    "excessive hunger"	:	    "excessive_hunger"	,
    "extra marital contacts"	:	    "extra_marital_contacts"	,
    "family history"	:	    "family_history"	,
    "fast heart rate"	:	    "fast_heart_rate"	,
    "fatigue"	:	    "fatigue"	,
    "fluid overload"	:	    "fluid_overload"	,
    "foul smell of urine"	:	    "foul_smell_of urine"	,
    "headache"	:	    "headache"	,
    "high fever"	:	    "high_fever"	,
    "hip joint pain"	:	    "hip_joint_pain"	,
    "history of alcohol consumption"	:	    "history_of_alcohol_consumption"	,
    "increased appetite"	:	    "increased_appetite"	,
    "indigestion"	:	    "indigestion"	,
    "inflammatory nails"	:	    "inflammatory_nails"	,
    "internal itching"	:	    "internal_itching"	,
    "irregular sugar level"	:	    "irregular_sugar_level"	,
    "irritability"	:	    "irritability"	,
    "irritation in anus"	:	    "irritation_in_anus"	,
    "itching"	:	    "itching"	,
    "joint pain"	:	    "joint_pain"	,
    "knee pain"	:	    "knee_pain"	,
    "lack of concentration"	:	    "lack_of_concentration"	,
    "lethargy"	:	    "lethargy"	,
    "loss of appetite"	:	    "loss_of_appetite"	,
    "loss of balance"	:	    "loss_of_balance"	,
    "loss of smell"	:	    "loss_of_smell"	,
    "malaise"	:	    "malaise"	,
    "mild fever"	:	    "mild_fever"	,
    "mood swings"	:	    "mood_swings"	,
    "movement stiffness"	:	    "movement_stiffness"	,
    "mucoid sputum"	:	    "mucoid_sputum"	,
    "muscle pain"	:	    "muscle_pain"	,
    "muscle wasting"	:	    "muscle_wasting"	,
    "muscle weakness"	:	    "muscle_weakness"	,
    "nausea"	:	    "nausea"	,
    "neck pain"	:	    "neck_pain"	,
    "nodal skin eruptions"	:	    "nodal_skin_eruptions"	,
    "obesity"	:	    "obesity"	,
    "pain behind the eyes"	:	    "pain_behind_the_eyes"	,
    "pain during bowel movements"	:	    "pain_during_bowel_movements"	,
    "pain in anal region"	:	    "pain_in_anal_region"	,
    "painful walking"	:	    "painful_walking"	,
    "palpitations"	:	    "palpitations"	,
    "passage of gases"	:	    "passage_of_gases"	,
    "patches in throat"	:	    "patches_in_throat"	,
    "phlegm"	:	    "phlegm"	,
    "polyuria"	:	    "polyuria"	,
    "prognosis"	:	    "prognosis"	,
    "prominent veins on calf"	:	    "prominent_veins_on_calf"	,
    "puffy face and eyes"	:	    "puffy_face_and_eyes"	,
    "pus filled pimples"	:	    "pus_filled_pimples"	,
    "receiving blood transfusion"	:	    "receiving_blood_transfusion"	,
    "receiving unsterile injections"	:	    "receiving_unsterile_injections"	,
    "red sore around nose"	:	    "red_sore_around_nose"	,
    "red spots over body"	:	    "red_spots_over_body"	,
    "redness of eyes"	:	    "redness_of_eyes"	,
    "restlessness"	:	    "restlessness"	,
    "runny nose"	:	    "runny_nose"	,
    "rusty sputum"	:	    "rusty_sputum"	,
    "scurring"	:	    "scurring"	,
    "shivering"	:	    "shivering"	,
    "silver like dusting"	:	    "silver_like_dusting"	,
    "sinus pressure"	:	    "sinus_pressure"	,
    "skin peeling"	:	    "skin_peeling"	,
    "skin rash"	:	    "skin_rash"	,
    "slurred speech"	:	    "slurred_speech"	,
    "small dents in nails"	:	    "small_dents_in_nails"	,
    "spinning movements"	:	    "spinning_movements"	,
    "spotting urination"	:	    "spotting_ urination"	,
    "stiff neck"	:	    "stiff_neck"	,
    "stomach bleeding"	:	    "stomach_bleeding"	,
    "stomach pain"	:	    "stomach_pain"	,
    "sunken eyes"	:	    "sunken_eyes"	,
    "sweating"	:	    "sweating"	,
    "swelled lymph nodes"	:	    "swelled_lymph_nodes"	,
    "swelling joints"	:	    "swelling_joints"	,
    "swelling of stomach"	:	    "swelling_of_stomach"	,
    "swollen blood vessels"	:	    "swollen_blood_vessels"	,
    "swollen extremeties"	:	    "swollen_extremeties"	,
    "swollen legs"	:	    "swollen_legs"	,
    "throat irritation"	:	    "throat_irritation"	,
    "toxic look (typhos)"	:	    "toxic_look_(typhos)"	,
    "ulcers on tongue"	:	    "ulcers_on_tongue"	,
    "unsteadiness"	:	    "unsteadiness"	,
    "visual disturbances"	:	    "visual_disturbances"	,
    "vomiting"	:	    "vomiting"	,
    "watering from eyes"	:	    "watering_from_eyes"	,
    "weakness in limbs"	:	    "weakness_in_limbs"	,
    "weakness of one body side"	:	    "weakness_of_one_body_side"	,
    "weight gain"	:	    "weight_gain"	,
    "weight loss"	:	    "weight_loss"	,
    "yellow crust ooze"	:	    "yellow_crust_ooze"	,
    "yellow urine"	:	    "yellow_urine"	,
    "yellowing of eyes"	:	    "yellowing_of_eyes"	,
    "yellowish skin"	:	    "yellowish_skin"	,
	}
    

selected_option = st.selectbox("Select an option:", list(options.keys()))

if st.button('Predicted Disease'):
    Symptom1=selected_option
st.write('you select\n',Symptom1)
for k,v in enumerate(d1):
    if(Symptom1==k):
        data[int(v)]=1

st.write('array\n',k)
if(selected=='Consult Specialist'):
    st.title('Dr. specialization Prediction Uising Random Forest in ML')
    
    